timezone: Asia/Shanghai
schedule:
  - "02:00"
  - "06:00"
  - "10:00"
  - "14:00"

assets:
- name: 财通成长优选混合C
  code: jj021528
  kind: fund
- name: 科创100ETF南方
  code: sh588900
  kind: etf
- name: 建信新兴市场混合(QDII)C
  code: jj018147
  kind: fund

channels:
  pushplus:
    token_env: PUSHPLUS_TOKEN
